// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv`

interface CloudflareEnv {
	OAUTH_KV: KVNamespace;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").OfficeMCP>;
	WHITELIST_USERS?: string;
	WHITELIST_DOMAINS?: string;
}
