name = "mcp-gdrive-fileaccess"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "b4385b722179437a8e827f199de27580"

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "OfficeMCP" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OfficeMCP"]

[observability]
enabled = true
